### ISSUE TITLE
PKGBUILD for Arch Linux

### ISSUE THREAD

**Issue by thiagowfx** [denilsonsa/arandr-indicator#2]
Hi Denilson,

Passing by to say that I've just created a PKGBUILD for your indicator. It is [here](https://aur.archlinux.org/packages/arandr-indicator-git/).

**Comment by denilsonsa** [comment]
Thanks! I've updated the README to link to your package.

Você também faz/fez computação na UFRJ? :)

**Comment by thiagowfx** [comment]
Faço, mas não a que você deve estar pensando ;)
Engenharia de Computação e Informação, na verdade.

Também vi que temos uns contatos em comum da Maratona (Buss, Bola, etc).

Até por aí, abraços
