### ISSUE TITLE
Order of scripts available "hybrid_3-screens.sh"

### ISSUE THREAD

**Issue by mxmilkiib** [denilsonsa/arandr-indicator#6]
I have  "hybrid_4-screens.sh" and  "hybrid_4-screens-toptvclone.sh" but the former is listed after the latter. Might it be possible to have the shorter "hybrid_4-screens.sh" be shown first? Thanks!

![image](https://github.com/denilsonsa/arandr-indicator/assets/108225/7dc3d347-1db6-4d23-9831-fe7456074eb9)

**Comment by denilsonsa** [comment]
Hmmm, interesting, I didn't think about this corner case

```
In [1]: a = ["hybrid_4-screens.sh", "hybrid_4-screens-toptvclone.sh"]

In [2]: sorted(a)
Out[2]: ['hybrid_4-screens-toptvclone.sh', 'hybrid_4-screens.sh']

In [3]: sorted(s.replace('.sh', '') for s in a)
Out[3]: ['hybrid_4-screens', 'hybrid_4-screens-toptvclone']
```

**Comment by mxmilkiib** [comment]
Thanks!
